# Generated by Django 4.1.5 on 2023-01-10 04:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0002_remove_commentmodel_website_commentmodel_phone'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CommentModel',
        ),
    ]
